"""Initial database schema

Revision ID: 52f9e16b6701
Revises: 
Create Date: 2026-08-19 00:30:41.466017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52f9e16b6701'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('exam_year', sa.SmallInteger(), nullable=True),
    sa.Column('easy_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('hard_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_difficulty_stats_dimension', 'difficulty_stats', ['dimension', 'dimension_id'], unique=False)
    op.create_index('idx_difficulty_stats_year', 'difficulty_stats', ['exam_year'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stages_completed', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_jobs_paper_id', 'processing_jobs', ['paper_id'], unique=False)
    op.create_index('idx_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_semesters_number', 'semesters', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('super_admin', 'admin', 'student')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_bookmarks_user_entity')
    )
    op.create_index('idx_bookmarks_entity', 'bookmarks', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_bookmarks_user_id', 'bookmarks', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_type', 'recommendations', ['recommendation_type'], unique=False)
    op.create_index('idx_recommendations_user_id', 'recommendations', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_index('idx_search_history_subject_id', 'search_history', ['subject_id'], unique=False)
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_table('student_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_activity_created_at', 'student_activity', ['created_at'], unique=False)
    op.create_index('idx_student_activity_type', 'student_activity', ['activity_type'], unique=False)
    op.create_index('idx_student_activity_user_id', 'student_activity', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semester_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_subjects_code', 'subjects', ['code'], unique=True)
    op.create_index('idx_subjects_semester_id', 'subjects', ['semester_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_type', 'subject_id', name='uq_analytics_snapshots_type_subject')
    )
    op.create_index('idx_analytics_snapshots_subject_id', 'analytics_snapshots', ['subject_id'], unique=False)
    op.create_index('idx_analytics_snapshots_type', 'analytics_snapshots', ['snapshot_type'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=True),
    sa.Column('exam_year', sa.SmallInteger(), nullable=False),
    sa.Column('exam_month', sa.String(length=20), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('total_marks', sa.SmallInteger(), nullable=True),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('processing_job_id', sa.String(length=36), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_papers_exam_year', 'papers', ['exam_year'], unique=False)
    op.create_index('idx_papers_processing_status', 'papers', ['processing_status'], unique=False)
    op.create_index('idx_papers_semester_id', 'papers', ['semester_id'], unique=False)
    op.create_index('idx_papers_subject_id', 'papers', ['subject_id'], unique=False)
    op.create_index('idx_papers_subject_year', 'papers', ['subject_id', 'exam_year'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('unit_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weightage_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'unit_number', name='uq_units_subject_number')
    )
    op.create_index('idx_units_subject_id', 'units', ['subject_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topics_subject_id', 'topics', ['subject_id'], unique=False)
    op.create_index('idx_topics_unit_id', 'topics', ['unit_id'], unique=False)
    op.create_table('unit_weightage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('weightage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_index('idx_unit_weightage_subject_id', 'unit_weightage', ['subject_id'], unique=False)
    op.create_table('dependency_graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_topic_id', sa.String(length=36), nullable=False),
    sa.Column('to_topic_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_topic_id', 'to_topic_id', name='uq_dep_graph_edge')
    )
    op.create_index('idx_dep_graph_from', 'dependency_graph_edges', ['from_topic_id'], unique=False)
    op.create_index('idx_dep_graph_subject', 'dependency_graph_edges', ['subject_id'], unique=False)
    op.create_index('idx_dep_graph_to', 'dependency_graph_edges', ['to_topic_id'], unique=False)
    op.create_table('predicted_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks_estimated', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('difficulty_estimated', sa.String(length=10), nullable=True),
    sa.Column('probability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('generation_rationale', sa.Text(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ai_disclaimer', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generation_batch_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ai_disclaimer IS NOT NULL AND length(ai_disclaimer) > 10', name='ck_predicted_questions_disclaimer'),
    sa.CheckConstraint('is_ai_generated = TRUE', name='ck_predicted_questions_is_ai'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predicted_questions_subject_id', 'predicted_questions', ['subject_id'], unique=False)
    op.create_index('idx_predicted_questions_topic_id', 'predicted_questions', ['topic_id'], unique=False)
    op.create_table('probability_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_probability_scores_subject_id', 'probability_scores', ['subject_id'], unique=False)
    op.create_index('idx_probability_scores_topic_id', 'probability_scores', ['topic_id'], unique=False)
    op.create_table('question_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_label', sa.String(length=500), nullable=False),
    sa.Column('centroid_embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('representative_question_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_clusters_subject_id', 'question_clusters', ['subject_id'], unique=False)
    op.create_index('idx_question_clusters_topic_id', 'question_clusters', ['topic_id'], unique=False)
    op.create_table('topic_trends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('exam_year', sa.SmallInteger(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('avg_difficulty', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'exam_year', name='uq_topic_trends_topic_year')
    )
    op.create_index('idx_topic_trends_subject_id', 'topic_trends', ['subject_id'], unique=False)
    op.create_index('idx_topic_trends_topic_id', 'topic_trends', ['topic_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('difficulty_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('exam_year', sa.SmallInteger(), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('is_repeated', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.SmallInteger(), nullable=False),
    sa.Column('ai_classification_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_cluster_id', 'questions', ['cluster_id'], unique=False)
    op.create_index('idx_questions_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('idx_questions_exam_year', 'questions', ['exam_year'], unique=False)
    op.create_index('idx_questions_paper_id', 'questions', ['paper_id'], unique=False)
    op.create_index('idx_questions_subject_id', 'questions', ['subject_id'], unique=False)
    op.create_index('idx_questions_topic_id', 'questions', ['topic_id'], unique=False)
    op.create_index('idx_questions_topic_year', 'questions', ['topic_id', 'exam_year'], unique=False)
    op.create_index('idx_questions_unit_id', 'questions', ['unit_id'], unique=False)
    op.create_table('question_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('chroma_doc_id', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('idx_question_embeddings_question_id', 'question_embeddings', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_question_embeddings_question_id', table_name='question_embeddings')
    op.drop_table('question_embeddings')
    op.drop_index('idx_questions_unit_id', table_name='questions')
    op.drop_index('idx_questions_topic_year', table_name='questions')
    op.drop_index('idx_questions_topic_id', table_name='questions')
    op.drop_index('idx_questions_subject_id', table_name='questions')
    op.drop_index('idx_questions_paper_id', table_name='questions')
    op.drop_index('idx_questions_exam_year', table_name='questions')
    op.drop_index('idx_questions_difficulty', table_name='questions')
    op.drop_index('idx_questions_cluster_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_topic_trends_topic_id', table_name='topic_trends')
    op.drop_index('idx_topic_trends_subject_id', table_name='topic_trends')
    op.drop_table('topic_trends')
    op.drop_index('idx_question_clusters_topic_id', table_name='question_clusters')
    op.drop_index('idx_question_clusters_subject_id', table_name='question_clusters')
    op.drop_table('question_clusters')
    op.drop_index('idx_probability_scores_topic_id', table_name='probability_scores')
    op.drop_index('idx_probability_scores_subject_id', table_name='probability_scores')
    op.drop_table('probability_scores')
    op.drop_index('idx_predicted_questions_topic_id', table_name='predicted_questions')
    op.drop_index('idx_predicted_questions_subject_id', table_name='predicted_questions')
    op.drop_table('predicted_questions')
    op.drop_index('idx_dep_graph_to', table_name='dependency_graph_edges')
    op.drop_index('idx_dep_graph_subject', table_name='dependency_graph_edges')
    op.drop_index('idx_dep_graph_from', table_name='dependency_graph_edges')
    op.drop_table('dependency_graph_edges')
    op.drop_index('idx_unit_weightage_subject_id', table_name='unit_weightage')
    op.drop_table('unit_weightage')
    op.drop_index('idx_topics_unit_id', table_name='topics')
    op.drop_index('idx_topics_subject_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_units_subject_id', table_name='units')
    op.drop_table('units')
    op.drop_index('idx_papers_subject_year', table_name='papers')
    op.drop_index('idx_papers_subject_id', table_name='papers')
    op.drop_index('idx_papers_semester_id', table_name='papers')
    op.drop_index('idx_papers_processing_status', table_name='papers')
    op.drop_index('idx_papers_exam_year', table_name='papers')
    op.drop_table('papers')
    op.drop_index('idx_analytics_snapshots_type', table_name='analytics_snapshots')
    op.drop_index('idx_analytics_snapshots_subject_id', table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index('idx_subjects_semester_id', table_name='subjects')
    op.drop_index('idx_subjects_code', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('idx_student_activity_user_id', table_name='student_activity')
    op.drop_index('idx_student_activity_type', table_name='student_activity')
    op.drop_index('idx_student_activity_created_at', table_name='student_activity')
    op.drop_table('student_activity')
    op.drop_index('idx_search_history_user_id', table_name='search_history')
    op.drop_index('idx_search_history_subject_id', table_name='search_history')
    op.drop_index('idx_search_history_created_at', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('idx_recommendations_user_id', table_name='recommendations')
    op.drop_index('idx_recommendations_type', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_bookmarks_user_id', table_name='bookmarks')
    op.drop_index('idx_bookmarks_entity', table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_semesters_number', table_name='semesters')
    op.drop_table('semesters')
    op.drop_index('idx_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('idx_processing_jobs_paper_id', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('idx_difficulty_stats_year', table_name='difficulty_stats')
    op.drop_index('idx_difficulty_stats_dimension', table_name='difficulty_stats')
    op.drop_table('difficulty_stats')
    # ### end Alembic commands ###
